version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: olist
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d olist"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/olist
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      OLIST_PG_HOST: postgres
      OLIST_PG_PORT: 5432
      OLIST_PG_DB: olist
      OLIST_PG_USER: airflow
      OLIST_PG_PASSWORD: airflow
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"
    user: "0:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: olist_airflow_webserver
    command: webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/olist
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      OLIST_PG_HOST: postgres
      OLIST_PG_PORT: 5432
      OLIST_PG_DB: olist
      OLIST_PG_USER: airflow
      OLIST_PG_PASSWORD: airflow
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: olist_airflow_scheduler
    command: scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/olist
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      OLIST_PG_HOST: postgres
      OLIST_PG_PORT: 5432
      OLIST_PG_DB: olist
      OLIST_PG_USER: airflow
      OLIST_PG_PASSWORD: airflow
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: olist_spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8081:8080"
    restart: always

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: olist_spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    restart: always

  jupyter:
    image: jupyter/base-notebook
    container_name: olist_jupyter
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    depends_on:
      postgres:
        condition: service_healthy

  metabase:
    image: metabase/metabase
    container_name: olist_metabase
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./metabase-data:/metabase.db
    depends_on:
      postgres:
        condition: service_healthy

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: olist_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: olist_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
